Traceback (most recent call last):
  File "D:/Software/MCL/pythonfiles/Chapter10/test.py", line 8, in error
    raise Exception("엀엀엀엀엀엀엀미미미미")
Exception: 엀엀엀엀엀엀엀미미미미
